import SideNav from "@/app/_components/board/SideNav";
import React from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col h-screen md:flex-row md:overflow-hidden">
      <div className="w-full md:w-64">
          <SideNav />
      </div>
      <div className="border-4 flex-grow">
          {children}
      </div>
    </div>
  )
}
